### ISSUE TITLE
Generic error: Querier contract error: terraswap::asset::PairInfoRaw not found: contract query failed: execute wasm contract failed

### ISSUE THREAD

**Issue by logesh2496** [Mirror-Protocol/mirror-contracts#74]
**Describe the bug**
Getting `Querier contract error: terraswap::asset::PairInfoRaw not found` when trying to invoke **post_initialize** method after instantiating the mirror_factory.

Failed transaction: https://finder.terra.money/bombay-10/tx/1FCBFA0CD846639888DEEA0A6263DD28F3D6F300F7899F7228AFD3992BA21112

**To Reproduce**
Mirror_Factory contract address on bombay-10: https://finder.terra.money/bombay-10/address/terra1m2s8897sgf5pxdpr4t78dpvyctkh7awamnyffj
1. Instantiate the contract
2. Try to execute post_initialize method.

**Context & versions**
Using current Main branch of [mirror-contracts](https://github.com/Mirror-Protocol/mirror-contracts) and [terraswap](https://github.com/terraswap/terraswap).

**(if applicable) suggested solution**
If you know the solution to the bug, let us know!

**Comment by csanti** [comment]
Hey @logesh2496,

I think the issue might be related to how you instantiated MIR. For Mirror Factory instantiation you need to previously have instantiated MIR token, and created the pair through terraswap factory. After you have MIR token and pair registered in terraswap factory then you can execute `PostInitialize`.

I suspect that you didn't create the MIR pair and that is why you get the error "PairInfo not found".

See: https://github.com/Mirror-Protocol/mirror-contracts/blob/a76fd3c61b36d1111125a94ff5efff82285adb5d/contracts/mirror_factory/src/contract.rs#L149

Please try that, and let us know if you are still having issues.

**Comment by logesh2496** [comment]
Hey @csanti,
Yes, that must be the problem, thanks for such detailed explanation. 
I'm now following the [integration-test](https://github.com/Mirror-Protocol/mirror.js/blob/main/integration-test/deploy.ts) in mirror.js to deploy the contracts. Its working except after staking the LP tokens, the reward of native token is always 0. Could you please help me with that?
(Note: I'm even calling the distribute method from mirror factory every now and then. But it seems that the native tokens are not minted at all)
